#!/usr/bin/env ruby

require 'optparse'
require 'fileutils'

$opts, $files = {}, {}

OptionParser.new do |opts|
  opts.banner = "Usage: #{$0} [options] DIR_1 ... DIR_N"

  opts.separator ''
  opts.separator 'Options:'
  opts.separator ''

  $opts[:output_dir] = 'sorted'
  opts.on '-o', '--output-dir DIRECTORY', 'Directory into which renamed files are copied' do |dir|
    $opts[:output_dir] = dir
  end

  $opts[:prefix] = 'DSC_'
  opts.on '-p', '--prefix PREFIX', 'Prefix to include before number.' do |prefix|
    $opts[:prefix] = prefix
  end

  $opts[:digits] = 4
  opts.on '-n', '--digits NUM', 'Number of digits to include in file numbers.' do |digits|
    $opts[:digits] = digits.to_i
  end
end.parse!

FileUtils.mkdir_p $opts[:output_dir]

def process file
  return if File.directory? file

  mtime = File.mtime file
 
  $files[file] = mtime
end

ARGV.each do |input_dir|
  unless File.directory? input_dir
    $stderr.puts "Warning: skipping nonexistent directory \"#{input_dir}\""
    next
  end

  Dir["#{input_dir}/**/*"].each { |f| process f }
end

# XXX: create multiple sub-directories inside output_dir and restart numbering
# XXX: also handle 0 digit case, since we might not need padding, making this
#      problem irrelevant
if $files.length.to_s.length > $opts[:digits]
  abort 'error: need more prefix digits for this many files'
end

result = $files.sort_by {|n, v| v}

result.each_with_index do |(file, mtime), num|
  ext = File.extname file
  num = num.to_s.rjust $opts[:digits], '0'

  output_file = "#{$opts[:output_dir]}/#{$opts[:prefix]}#{num}#{ext}"

  puts "#{file} -> #{output_file}"

  FileUtils.cp file, output_file
end

